sudo: required

language: bash

branches:
  only:
  - master
  - production

services:
  - docker

before_install:
   - docker build -t madsequipo2/mads-equipo2-201718:$TRAVIS_BUILD_NUMBER .

script:
   - docker run --rm madsequipo2/mads-equipo2-201718:$TRAVIS_BUILD_NUMBER /bin/bash -c "sbt test"
   - docker run -d --rm -p 3306:3306 --name play-mysql -e MYSQL_DATABASE="mads" -e MYSQL_ROOT_PASSWORD="mads" mysql
   - docker run --link play-mysql:mysql --rm -e DB_URL="jdbc:mysql://play-mysql:3306/mads" -e DB_USER_NAME="root" -e DB_USER_PASSWD="mads" -v${PWD}:/code madsequipo2/mads-equipo2-201718:$TRAVIS_BUILD_NUMBER /bin/bash -c "./runsbttest.sh"


after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "diegomgar" -p "mipassmads1234";
    docker push madsequipo2/mads-equipo2-201718:$TRAVIS_BUILD_NUMBER;
    docker push madsequipo2/mads-equipo2-201718:latest;
    fi
