sudo: required

language: bash

branches:
  - master
  - production

services:
  - docker

before_install:
   - docker build -t madsequipo2/mads-equipo2-201718:$TRAVIS_BUILD_NUMBER .

script:
   - docker run --rm madsequipo2/mads-equipo2-201718 /bin/bash -c "sbt test"

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "diegomgar" -p "mipassmads1234";
    docker push madsequipo2/mads-equipo2-201718:$TRAVIS_BUILD_NUMBER;
    docker push madsequipo2/mads-equipo2-201718:latest;
    fi
