sudo: required

language: bash

services:
  - docker

before_install:
   - docker build -t madsequipo2/mads-equipo2-201718 .

script:
   - docker run --rm madsequipo2/mads-equipo2-201718 /bin/bash -c "sbt test"